#!/usr/bin/env python3
"""Write the scan status where the hardened web app can read it.
usage: reading-room-write-status STATE MESSAGE [EXTRA_JSON]"""
import json, os, pwd, sys, time
state, message = sys.argv[1], sys.argv[2]
extra = json.loads(sys.argv[3]) if len(sys.argv) > 3 else {}
path = "/var/lib/reading-room/scan-status.json"
body = dict(extra, state=state, message=message, at=time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()))
tmp = path + ".new"
with open(tmp, "w") as fh:
    json.dump(body, fh)
u = pwd.getpwnam("reading-room")
os.chown(tmp, u.pw_uid, u.pw_gid)
os.chmod(tmp, 0o644)
os.replace(tmp, path)
