import test from 'node:test';
import assert from 'node:assert/strict';
import { pathToFileURL } from 'node:url';
import { reliabilityPreview } from './reliability-preview.mjs';
import { narrationEpub } from './epub-fixture.mjs';
const pw = await import(process.env.HOME_BOOKS_PLAYWRIGHT ? pathToFileURL(process.env.HOME_BOOKS_PLAYWRIGHT).href : 'playwright');

for (const engine of ['chromium','webkit']) test(`${engine}: pause preserves scroll and explicit return finds narration from ahead or behind`, {timeout:45000}, async t => {
  const preview=await reliabilityPreview(); t.after(()=>preview.close());
  const browser=await pw[engine].launch(engine==='chromium'&&process.env.READING_ROOM_CHROME?{executablePath:process.env.READING_ROOM_CHROME}:{}); t.after(()=>browser.close());
  const page=await browser.newPage({viewport:{width:393,height:852},serviceWorkers:'block'});
  const errors=[]; page.on('pageerror',e=>errors.push(e.message));
  const fixture=await narrationEpub({chapterCount:5,paragraphCount:65});
  await page.route('**/catalog.json',r=>r.fulfill({json:[{id:'position-fixture',title:'Narration position',format:'EPUB',source:'Local'}]}));
  await page.route('**/api/library-state',r=>r.fulfill({json:{states:[]}}));
  await page.route('**/api/book/**',r=>r.fulfill({contentType:'application/epub+zip',body:fixture}));
  await page.route('**/api/tts/voices',r=>r.fulfill({json:{voices:[{id:'en_GB-alba-medium',label:'Alba'}]}}));
  await page.route('**/api/tts?**',r=>r.fulfill({body:'fixture'}));
  await page.addInitScript(()=>{
    localStorage.setItem('reading-room-reader-mode','scroll');
    Object.defineProperty(HTMLMediaElement.prototype,'src',{configurable:true,get(){return this.fixtureSrc||''},set(v){this.fixtureSrc=v}});
    HTMLMediaElement.prototype.load=function(){};
    HTMLMediaElement.prototype.play=function(){this.onplaying?.();return Promise.resolve()};
    HTMLMediaElement.prototype.pause=function(){};
  });
  await page.goto(preview.url);
  await page.locator('.rr-library-dock button[data-view="Library"]').click();
  await page.locator('.book .cover').click();
  await page.locator('.epub-viewer iframe').first().waitFor();
  const scroller=page.locator('.epub-container');
  await scroller.evaluate(el=>{el.scrollTop=1600}); await page.waitForTimeout(800);
  const menu=page.locator('.rr-react-sheet-trigger'); await menu.click();
  await page.locator('[data-view="menu"] button').filter({hasText:/^Aloud$/}).click();
  await page.getByRole('button',{name:'Start reading',exact:true}).click();
  await page.waitForFunction(()=>!!document.querySelector('#rr-tts-audio')?.src);
  await menu.click(); await page.waitForTimeout(700);
  const source=await page.locator('#rr-tts-audio').evaluate(a=>a.src);
  const spoken=await scroller.evaluate(el=>el.scrollTop);
  await scroller.evaluate(el=>{el.scrollTop+=1100}); await page.waitForTimeout(500);
  const beforePause=await scroller.evaluate(el=>el.scrollTop);
  await page.getByRole('button',{name:'Pause read aloud',exact:true}).click();
  await page.waitForTimeout(600);
  assert.ok(Math.abs(await scroller.evaluate(el=>el.scrollTop)-beforePause)<3,'pause must not relocate the page');
  const jump=page.getByRole('button',{name:'Return to current reading',exact:true});
  await jump.click(); await page.waitForTimeout(800);
  const returned=await scroller.evaluate(el=>el.scrollTop);
  assert.ok(Math.abs(returned-spoken)<100,'return finds spoken sentence from ahead');
  await scroller.evaluate(el=>{el.scrollTop=Math.max(0,el.scrollTop-1000)}); await page.waitForTimeout(600);
  await jump.click(); await page.waitForTimeout(800);
  assert.ok(Math.abs(await scroller.evaluate(el=>el.scrollTop)-returned)<3,'return finds same sentence from behind');
  assert.equal(await page.locator('#rr-tts-audio').evaluate(a=>a.src),source,'return must not restart or replace audio');
  assert.equal(await page.getByRole('button',{name:'Resume read aloud',exact:true}).count(),1,'return preserves paused state');
  assert.deepEqual(errors,[]);
});
