import assert from 'node:assert/strict';
import test from 'node:test';
import {launchBrowser} from './cdp-browser.mjs';

for (const mode of ['scroll', 'pages']) test(`Demons and Druids ${mode} narration crosses prologue/part/chapter without rewinding`, {timeout:90000}, async t=>{
 const b=await launchBrowser();t.after(()=>b.close());
 const errors=[];b.on('Runtime.exceptionThrown',e=>errors.push(e.exceptionDetails.exception?.description||e.exceptionDetails.text));
 await b.send('Page.addScriptToEvaluateOnNewDocument',{source:`
 localStorage.setItem('reading-room-reader-mode',${JSON.stringify(mode)});
 window.boundaries=[];
 const fetchOriginal=window.fetch;
 window.fetch=(input,opts)=>{const p=new URL(typeof input==='string'?input:input.url,location.href).pathname;
 if(p==='/catalog.json')return Promise.resolve(new Response(JSON.stringify([{id:'L00b856950ddb400a2f8846ad58a4c9519a9ce687',title:'Demons and Druids',author:'James Patterson',format:'EPUB',source:'Local',url:'/api/book/L00b856950ddb400a2f8846ad58a4c9519a9ce687'}]),{headers:{'Content-Type':'application/json'}}));
 if(p==='/api/library-state')return Promise.resolve(new Response('{"states":[]}',{headers:{'Content-Type':'application/json'}}));
 if(p==='/api/tts'||p==='/api/tts/warm')return Promise.resolve(new Response('fixture'));
 return fetchOriginal(input,opts);};
 Object.defineProperty(HTMLMediaElement.prototype,'src',{configurable:true,get(){return this.fixtureSrc||''},set(v){this.fixtureSrc=v}});
 HTMLMediaElement.prototype.play=function(){clearTimeout(this.fixtureTimer);this.onplaying?.();this.fixtureTimer=setTimeout(()=>this.onended?.(),60);return Promise.resolve()};
 HTMLMediaElement.prototype.pause=function(){clearTimeout(this.fixtureTimer)};
 window.addEventListener('rr-narration',e=>{if(e.detail.kind==='sentence'){
 const c=window.r?.getContents().find(c=>c.document===e.detail.doc);
 window.boundaries.push({index:c?.sectionIndex,text:e.detail.range.toString()});
 }});
 `});
 await b.goto(process.env.READING_ROOM_BASE_URL||'http://127.0.0.1:48113');
 await b.waitFor(`!!document.querySelector('.rr-library-dock')`);
 await b.evaluate(`document.querySelector('.rr-library-dock button[data-view="Library"]').click()`);
 await b.waitFor(`!!document.querySelector('.book .cover')`);
 await b.evaluate(`document.querySelector('.book .cover').click()`);
 await b.waitFor(`!!document.querySelector('.epub-viewer iframe')`,{attempts:200});
 await b.evaluate(`void(window.r=(()=>{const n=document.querySelector('.epub-viewer');let f=n[Object.keys(n).find(k=>k.startsWith('__reactFiber'))];for(;f;f=f.return)for(let h=f.memoizedState;h&&typeof h==='object';h=h.next){const v=h.memoizedState?.current;if(v?.getContents&&v?.display)return v;}})())`);
 await b.evaluate(`void r.display('Text/Section0087.xhtml')`);
 await b.waitFor(`r.getContents().some(c=>c.sectionIndex===4)`);
 await new Promise(r=>setTimeout(r,900));
 if(mode==='scroll') await b.evaluate(`(()=>{const c=r.getContents().find(c=>c.sectionIndex===4),f=c.document.defaultView.frameElement,p=[...c.document.querySelectorAll('p')].filter(p=>p.textContent.trim()).at(-1);r.manager.container.scrollTop+=f.getBoundingClientRect().top+p.getBoundingClientRect().top-150;})()`);
 await new Promise(r=>setTimeout(r,700));
 await b.evaluate(`document.querySelector('.rr-react-sheet-trigger').click()`);
 await b.waitFor(`!!document.querySelector('[data-view="menu"]')`);
 await b.evaluate(`[...document.querySelectorAll('[data-view="menu"] button')].find(b=>b.textContent.includes('Aloud')).click()`);
 await b.waitFor(`!!document.querySelector('[data-view="aloud"]')`);
 await b.evaluate(`[...document.querySelectorAll('[data-view="aloud"] button')].find(b=>b.textContent.includes('Start reading')).click()`);
 await b.waitFor(`window.boundaries.some(e=>e.index>=7)`,{attempts:500,interval:100});
 await b.evaluate(`document.querySelector('button[aria-label="Pause read aloud"]')?.click()`);
 const events=await b.evaluate('window.boundaries');
 assert.equal(events[0].index,4,JSON.stringify({events:events.slice(0,3),frames:await b.evaluate(`r.getContents().map(c=>({index:c.sectionIndex,top:c.document.defaultView.frameElement.getBoundingClientRect().top,height:c.document.defaultView.frameElement.getBoundingClientRect().height}))`)}));
 assert.ok(events.some(e=>e.index===5&&/PART ONE/.test(e.text)), 'part heading is spoken');
 assert.ok(events.some(e=>e.index===6&&/Chapter 1/.test(e.text)), 'chapter begins at its heading');
 for(let i=1;i<events.length;i++)assert.ok(events[i].index>=events[i-1].index&&events[i].index<=events[i-1].index+1,JSON.stringify(events.slice(i-1,i+1)));
 assert.deepEqual(errors,[]);
 await new Promise(r=>setTimeout(r,300));
 const pausedCount=await b.evaluate('window.boundaries.length');
 await new Promise(r=>setTimeout(r,300));
 assert.equal(await b.evaluate('window.boundaries.length'),pausedCount,'pause stops sentence advancement');
 const beforeJump=await b.evaluate('window.boundaries.at(-1).index');
 await b.evaluate(`window.dispatchEvent(new CustomEvent('rr-narration-chapter',{detail:{delta:1}}))`);
 await b.waitFor(`window.boundaries.length>${pausedCount}`,{attempts:100});
 assert.ok(await b.evaluate(`window.boundaries[${pausedCount}].index>${beforeJump}`),'explicit chapter jump discards the previous sentence queue');
 await b.evaluate(`document.querySelector('button[aria-label="Pause read aloud"]')?.click()`);
 await b.screenshot(`demons-narration-boundary-${mode}.png`);
});
