// Renders overrides/index.template.html against the hashes this build produced.
//
// index.html cannot be regenerated by the build: it is a prerendered RSC
// document, and the app is served by a standalone server rather than by the
// worker the build targets. Everything in it is stable across builds except
// the content-hashed asset filenames and the override version, so the
// committed template carries the document and this script fills in the rest.
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const manifest = (await import(join(root, "dist/server/__vite_rsc_assets_manifest.js"))).default;
const version = (await readFile(join(root, "overrides/VERSION"), "utf8")).trim();

const base = (path) => path.replace(/^\/assets\//, "");
// The LibraryClient client reference. Its id is derived from the module path,
// not its contents, so it is stable across builds.
const deps = Object.values(manifest.clientReferenceDeps).find((entry) =>
  entry.js.some((path) => /\/LibraryClient-/.test(path)),
);
if (!deps) throw new Error("no LibraryClient client reference in the manifest");

const pick = (pattern, from) => {
  const hit = from.find((path) => pattern.test(path));
  if (!hit) throw new Error(`no asset matching ${pattern}`);
  return base(hit);
};
const layout = Object.values(manifest.clientReferenceDeps).flatMap((entry) => entry.js);
const css = Object.values(manifest.serverResources).flatMap((entry) => entry.css);

const values = {
  CSS: pick(/\/index-.*\.css$/, css),
  INDEX_JS: pick(/\/index-[^/]*\.js$/, deps.js),
  LIBRARY_JS: pick(/\/LibraryClient-/, deps.js),
  FRAMEWORK_JS: pick(/\/framework-/, deps.js),
  RUNTIME_JS: pick(/\/rolldown-runtime-/, deps.js),
  LAYOUT_JS: pick(/\/layout-segment-context-/, layout),
  V: version,
};

let html = await readFile(join(root, "overrides/index.template.html"), "utf8");

// Library navigation, filter/sort controls, and Settings are now React-owned.
// The committed index predates that ownership marker, so reconcile it just as
// we do the serialized layout below.
if (!html.includes('name="rr-react-library-chrome"')) {
  html = html.replace("<head>", '<head><meta name="rr-react-library-chrome" content="1"/>');
}

// The committed HTML also carries vinext's serialized root-layout payload.
// Theme boot intentionally adds data-rr-theme to <html> before hydration, so
// the payload must retain the matching suppressHydrationWarning from
// app/layout.tsx. The template predates that prop and otherwise silently
// overrides a clean build with its stale payload.
const rootLayout = '[\\"$\\",\\"html\\",null,{\\"lang\\":\\"en\\",\\"children\\"';
const tolerantRootLayout = '[\\"$\\",\\"html\\",null,{\\"lang\\":\\"en\\",\\"suppressHydrationWarning\\":true,\\"children\\"';
if (!html.includes(rootLayout) && !html.includes(tolerantRootLayout)) {
  throw new Error("root layout payload not found in index template");
}
html = html.replace(rootLayout, tolerantRootLayout);

// The template contains the serialized metadata emitted by the old root
// layout as well as the visible <meta> element above it.  Safari hydrates the
// serialized value later, so leaving "default" here turns a dark reader's
// status-bar strip light even though the first HTML paint is correct.
const defaultStatusBar = '\\"name\\":\\"apple-mobile-web-app-status-bar-style\\",\\"content\\":\\"default\\"';
const translucentStatusBar = '\\"name\\":\\"apple-mobile-web-app-status-bar-style\\",\\"content\\":\\"black-translucent\\"';
if (!html.includes(defaultStatusBar) && !html.includes(translucentStatusBar)) {
  throw new Error("serialized status-bar metadata not found in index template");
}
html = html.replaceAll(defaultStatusBar, translucentStatusBar);

// Keep the static first render in lockstep with LibraryClient. This app is
// deployed as a prerendered document, so the committed template is the server
// side of React hydration. These guarded replacements both reconcile the older
// template and fail loudly if its shape changes again instead of shipping a
// recoverable-but-noisy client redraw.
const initialMarkup = [
  ["<h1>Find your next book.</h1>", "<h1>Home</h1>"],
  ["<kbd>⌘ K</kbd>", "<kbd>Ctrl K</kbd>"],
  [
    '<div class="category-chips"><button>Fiction</button><button>Non-Fiction</button><button>Graphic Novels</button><button>Scripts</button><button>Readable here</button></div>',
    '<div class="category-chips"><button aria-pressed="false">Fiction</button><button aria-pressed="false">Non-Fiction</button><button aria-pressed="false">Graphic Novels</button><button aria-pressed="false">Scripts</button><button aria-pressed="false">Readable here</button></div>',
  ],
  [
    '<label><span>Series</span><select><option selected="">All series</option></select></label>',
    '<div class="filter-picker"><span>Series</span><button type="button" aria-haspopup="listbox" aria-expanded="false">All series<b aria-hidden="true">⌄</b></button></div>',
  ],
];
for (const [before, after] of initialMarkup) {
  if (!html.includes(before) && !html.includes(after)) {
    throw new Error(`initial markup target not found: ${before.slice(0, 60)}`);
  }
  html = html.replace(before, after);
}
for (const [key, value] of Object.entries(values)) html = html.replaceAll(`{{${key}}}`, value);
const unresolved = html.match(/\{\{[A-Z_]+\}\}/g);
if (unresolved) throw new Error(`unresolved placeholders: ${[...new Set(unresolved)].join(", ")}`);

await writeFile(join(root, "dist/index.html"), html);

console.log(Object.entries(values).map(([k, v]) => `  ${k} = ${v}`).join("\n"));
