// Renders overrides/index.template.html against the hashes this build produced.
//
// index.html cannot be regenerated by the build: it is a prerendered RSC
// document, and the app is served by a standalone server rather than by the
// worker the build targets. Everything in it is stable across builds except
// the content-hashed asset filenames and the override version, so the
// committed template carries the document and this script fills in the rest.
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const manifest = (await import(join(root, "dist/server/__vite_rsc_assets_manifest.js"))).default;
const version = (await readFile(join(root, "overrides/VERSION"), "utf8")).trim();

const base = (path) => path.replace(/^\/assets\//, "");
// The LibraryClient client reference. Its id is derived from the module path,
// not its contents, so it is stable across builds.
const deps = Object.values(manifest.clientReferenceDeps).find((entry) =>
  entry.js.some((path) => /\/LibraryClient-/.test(path)),
);
if (!deps) throw new Error("no LibraryClient client reference in the manifest");

const pick = (pattern, from) => {
  const hit = from.find((path) => pattern.test(path));
  if (!hit) throw new Error(`no asset matching ${pattern}`);
  return base(hit);
};
const layout = Object.values(manifest.clientReferenceDeps).flatMap((entry) => entry.js);
const css = Object.values(manifest.serverResources).flatMap((entry) => entry.css);

const values = {
  CSS: pick(/\/index-.*\.css$/, css),
  INDEX_JS: pick(/\/index-[^/]*\.js$/, deps.js),
  LIBRARY_JS: pick(/\/LibraryClient-/, deps.js),
  FRAMEWORK_JS: pick(/\/framework-/, deps.js),
  RUNTIME_JS: pick(/\/rolldown-runtime-/, deps.js),
  LAYOUT_JS: pick(/\/layout-segment-context-/, layout),
  V: version,
};

let html = await readFile(join(root, "overrides/index.template.html"), "utf8");

// The committed HTML also carries vinext's serialized root-layout payload.
// Theme boot intentionally adds data-rr-theme to <html> before hydration, so
// the payload must retain the matching suppressHydrationWarning from
// app/layout.tsx. The template predates that prop and otherwise silently
// overrides a clean build with its stale payload.
const rootLayout = '[\\"$\\",\\"html\\",null,{\\"lang\\":\\"en\\",\\"children\\"';
const tolerantRootLayout = '[\\"$\\",\\"html\\",null,{\\"lang\\":\\"en\\",\\"suppressHydrationWarning\\":true,\\"children\\"';
if (!html.includes(rootLayout) && !html.includes(tolerantRootLayout)) {
  throw new Error("root layout payload not found in index template");
}
html = html.replace(rootLayout, tolerantRootLayout);
for (const [key, value] of Object.entries(values)) html = html.replaceAll(`{{${key}}}`, value);
const unresolved = html.match(/\{\{[A-Z_]+\}\}/g);
if (unresolved) throw new Error(`unresolved placeholders: ${[...new Set(unresolved)].join(", ")}`);

await writeFile(join(root, "dist/index.html"), html);

// settings.html is a standalone static page, not part of the RSC build. It was
// live on the Pi with no source in the repo, so a deploy could never regenerate
// it and any edit survived only until the next one. It is a template here for
// the same reason index.html is: the only thing that varies is the version.
let settings = await readFile(join(root, "overrides/settings.template.html"), "utf8");
settings = settings.replaceAll("{{V}}", version);
const settingsUnresolved = settings.match(/\{\{[A-Z_]+\}\}/g);
if (settingsUnresolved) {
  throw new Error(`unresolved placeholders in settings: ${[...new Set(settingsUnresolved)].join(", ")}`);
}
await writeFile(join(root, "dist/settings.html"), settings);

console.log(Object.entries(values).map(([k, v]) => `  ${k} = ${v}`).join("\n"));
